[release]
address = "0.0.0.0"
log_level = "critical"

[default.tls]
certs = "/etc/letsencrypt/live/h2939250.stratoserver.net/fullchain.pem"
key = "/etc/letsencrypt/live/h2939250.stratoserver.net/privkey.pem"
